name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Assembly
        run: sbt assembly

      - name: Deploy to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target/scala-2.13/gRPC-Chat.jar
          remote: /home/botbek/builds/gRPC-Chat.jar
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
